import type { ClaimedRun } from '../../src/connector/types.js';
export const head='a'.repeat(40), base='b'.repeat(40), mergeSha='c'.repeat(40), localBase='e'.repeat(40);
export function mergeClaim():ClaimedRun { return {run:{id:'merge-run',projectId:'p',workId:'w',prompt:'',requestedBy:'owner',kind:'delivery',model:'internal',reasoning:'none',status:'running',generation:1,createdAt:'',updatedAt:'',operation:{action:'merge_pr',actorId:'owner',originalActorId:'owner',priorDeliveryRunId:'delivery-run',reviewRunId:'review-run',candidateRunId:'candidate',candidateRevision:'diff-r1',artifactRevision:'diff-r1',commitSha:head,candidateFingerprint:'d'.repeat(64),repositoryUrl:'https://github.com/org/repo',baseRevision:localBase,integrationBaseSha:base,baseBranch:'main',remoteBranch:'codex/menoteam/w/candidate',workTitle:'change',changeSummary:'src/file.ts',qaStatus:'passed',phase:'queued',mergeMethod:'merge',policySnapshot:{id:'setting',version:'v1',requiredChecks:['Menoteam CI']},external:{pullRequestNumber:4,pullRequestUrl:'https://github.com/org/repo/pull/4',pullRequestNodeId:'PR_fixture4',headSha:head,baseSha:base}}},project:{id:'p',name:'p',repositoryUrl:'https://github.com/org/repo',instructions:'',deliveryAuthorization:'',createdAt:''},messages:[],settings:[]}; }
export function mergeFixture(options:{duplicates?:Array<Partial<{appId:number;status:string;conclusion:string|null;headSha:string}>>;truncated?:boolean;nextPage?:boolean;appId?:number;protection?:boolean;stale?:boolean;failed?:boolean;missingCheck?:boolean;headChanged?:boolean;baseChanged?:boolean;bypass?:boolean;loseMergeResponse?:boolean;loseReadyResponse?:boolean;graphqlErrors?:boolean;unknownMerge?:boolean;badParents?:boolean;badAncestry?:boolean;draft?:boolean;merged?:boolean;dirty?:boolean;changeAfterReady?:boolean;strict?:boolean;admins?:boolean;emptyBypass?:boolean;behindCandidate?:boolean;graphState?:string;graphErrors?:boolean;identity?:{head:string;base:string;number:number;mergeSha?:string}}={}) {
 const mergeSha=options.identity?.mergeSha??'c'.repeat(40);
 const head=options.identity?.head??'a'.repeat(40),base=options.identity?.base??'b'.repeat(40),number=options.identity?.number??4,nodeId=`PR_fixture${number}`,urlPr=`https://github.com/org/repo/pull/${number}`;
 let draft=options.draft??true,merged=options.merged??false,writes=0,mergeCalls=0,readyCalls=0,gateReads=0;
 const fetcher=(async(input:RequestInfo|URL,init?:RequestInit)=>{
  const url=String(input);
  if(init?.method==='POST'&&url==='https://api.github.com/graphql') { const body=JSON.parse(String(init.body)); if(body.query.includes('query MergeState'))return options.graphErrors?Response.json({errors:[{message:'state unavailable'}]}):Response.json({data:{node:{id:nodeId,isDraft:draft,headRefOid:options.headChanged?'f'.repeat(40):head,baseRefOid:options.baseChanged?localBase:base,baseRefName:'main',mergeable:options.dirty?'CONFLICTING':'MERGEABLE',mergeStateStatus:options.graphState??(options.dirty?'BEHIND':draft?'DRAFT':'CLEAN')}}}); if(body.variables.id!==nodeId||!body.query.includes('markPullRequestReadyForReview'))throw Error('Wrong GraphQL identity');writes++;readyCalls++;if(options.graphqlErrors)return Response.json({errors:[{message:'denied'}]});draft=false;if(options.loseReadyResponse)throw Error('ready response lost');return Response.json({data:{markPullRequestReadyForReview:{pullRequest:{id:nodeId,isDraft:false}}}}); }
  if(init?.method==='PUT'&&url.endsWith('/merge')) {const body=JSON.parse(String(init.body));if(body.sha!==head||body.merge_method!=='merge')throw Error('wrong exact SHA/method');writes++;mergeCalls++;merged=!options.unknownMerge;if(options.loseMergeResponse||options.unknownMerge)throw Error('merge response lost');return Response.json({sha:mergeSha,merged:true,message:'merged'});}
  if(url.includes('/protection')){gateReads++;return options.protection===false?new Response('{}',{status:404}):Response.json({required_status_checks:{strict:options.strict??true,contexts:['Menoteam CI'],checks:[{context:'Menoteam CI',app_id:15368}]},enforce_admins:{enabled:options.admins??true},...((options.bypass||options.emptyBypass)?{required_pull_request_reviews:{bypass_pull_request_allowances:{apps:[],teams:[],users:options.bypass?[{id:1}]:[]}}}:{})});}
  if(url.includes('/check-runs')){const runs=options.missingCheck?[]:[{id:100,node_id:'CR_push',check_suite:{id:1001},pull_requests:[],name:'Menoteam CI',status:'completed',conclusion:options.failed||options.changeAfterReady&&!draft?'failure':'success',head_sha:options.stale?base:head,app:{id:options.appId??15368}}];for(const [index,extra] of (options.duplicates??[]).entries())runs.push({id:200+index,node_id:'CR_pr',check_suite:{id:2001+index},pull_requests:[{number}],name:'Menoteam CI',status:extra.status??'completed',conclusion:extra.conclusion===undefined?'success':extra.conclusion,head_sha:extra.headSha??head,app:{id:extra.appId??15368}} as typeof runs[number]);return Response.json({total_count:runs.length+(options.truncated?1:0),check_runs:runs},{headers:options.nextPage?{link:'<https://api.github.com/next>; rel="next"'}:{}});}
  if(url.endsWith(`/pulls/${number}`))return Response.json({number,node_id:nodeId,html_url:urlPr,state:merged?'closed':'open',draft,merged,mergeable:!options.dirty,head:{sha:options.headChanged?'f'.repeat(40):head,repo:{full_name:'org/repo'}},base:{ref:'main',sha:options.baseChanged?localBase:base,repo:{full_name:'org/repo'}},merge_commit_sha:merged?mergeSha:null});
  if(url.includes('/git/commits/'))return Response.json({sha:mergeSha,parents:[{sha:options.badParents?localBase:base},{sha:head}]});
  if(url.endsWith(`/compare/${base}...${head}`))return Response.json({status:options.behindCandidate?'diverged':'ahead',base_commit:{sha:base},merge_base_commit:{sha:options.behindCandidate?localBase:base}});
  if(url.includes('/compare/'))return Response.json({status:options.badAncestry?'diverged':'identical',merge_base_commit:{sha:mergeSha}});
  if(url.endsWith('/branches/main'))return Response.json({commit:{sha:merged?mergeSha:options.baseChanged?localBase:base}});
  throw Error(`unexpected fixture request ${init?.method??'GET'} ${url}`);
 }) as typeof fetch;
 return {fetcher,get writes(){return writes;},get mergeCalls(){return mergeCalls;},get readyCalls(){return readyCalls;},get gateReads(){return gateReads;}};
}
